variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    PYTHONDEVMODE: "1"
    RUNNER_GENERATE_ARTIFACTS_METADATA: "true"
    SLSA_PROVENANCE_SCHEMA_VERSION: "v1"

cache:
    paths:
        - ".cache/pip"

default:
    image: "docker.io/python:3"

lint:
    stage: "test"
    script:
        - "pip install flake8"
        - "flake8 --max-line-length=120 --ignore=W191,W503 ."

test:
    stage: "test"
    script:
        - "pip install pytest pexpect"
        - "pytest ."
